# Generated by Django 3.0.7 on 2020-06-21 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='doc',
            field=models.FileField(blank=True, null=True, upload_to='files'),
        ),
    ]
